version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: redmine-laravel-app
    volumes: 
      - ./:/var/www/html
    ports:
      - 9999:9999
    network_mode: "host"
